# Generated by Django 5.0.2 on 2026-02-16 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('due_date', models.DateField(blank=True, help_text='Task due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to complete the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Assignment group for the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group')),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this task for updates', related_name='watching_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique ticket number (9-character alphanumeric string)', max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, choices=[('email', 'Email'), ('web', 'Web/Portal'), ('phone', 'Phone'), ('chat', 'Live Chat'), ('chatbot', 'AI Chatbot'), ('api', 'API/Integrations'), ('internal', 'Internal/Staff-created'), ('customer_portal', 'Customer Portal')], default='web', help_text='How the ticket was created', max_length=20, null=True)),
                ('is_guest_ticket', models.BooleanField(default=False, help_text='Whether this ticket was created by a guest (non-authenticated user)')),
                ('guest_name', models.CharField(blank=True, help_text='Name of guest who created the ticket', max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email of guest who created the ticket', max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone number of guest who created the ticket', max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('type', models.CharField(choices=[('question', 'Question'), ('incident', 'Incident'), ('problem', 'Problem'), ('task', 'Task')], default='question', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Agent assigned to handle the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.department')),
                ('group', models.ForeignKey(blank=True, help_text='Assignment group for the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group')),
                ('requester', models.ForeignKey(blank=True, help_text='Person who submitted the ticket (null for guest tickets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this ticket for updates', related_name='watching_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='converted_from_ticket',
            field=models.ForeignKey(blank=True, help_text='Original ticket if this task was converted from a ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_tasks', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket this task is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='ticket.ticket'),
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('watcher_added', 'Watcher Added'), ('watcher_removed', 'Watcher Removed'), ('department_changed', 'Department Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('workitem_added', 'Work Item Added'), ('workitem_updated', 'Work Item Updated'), ('workitem_status_changed', 'Work Item Status Changed'), ('workitem_completed', 'Work Item Completed')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like old_value, new_value, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ticket.ticket')),
            ],
            options={
                'verbose_name_plural': 'Activity streams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the uploaded file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment objects with url, name, size, type')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note visible only to agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.ticketcomment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('work_notes', models.TextField(blank=True, help_text='Notes added when completing the work item')),
                ('due_date', models.DateField(blank=True, help_text='Work item due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to complete the work item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the work item', on_delete=django.db.models.deletion.CASCADE, related_name='created_work_items', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this work item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='ticket.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('watcher_added', 'Watcher Added'), ('watcher_removed', 'Watcher Removed'), ('group_changed', 'Group Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like old_value, new_value, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ticket.task')),
            ],
            options={
                'verbose_name_plural': 'Task activity streams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='ticket_task_task_id_a5dfa8_idx'), models.Index(fields=['activity_type'], name='ticket_task_activit_1dec48_idx'), models.Index(fields=['actor'], name='ticket_task_actor_i_f0ef59_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment objects with url, name, size, type')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note visible only to agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.task')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='ticket_task_task_id_fa5241_idx'), models.Index(fields=['author'], name='ticket_task_author__911691_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_tick_status_4da6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='ticket_tick_assigne_832c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester'], name='ticket_tick_request_1845d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='ticket_tick_priorit_58f4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='ticket_task_status_9accc8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='ticket_task_assigne_39363d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='ticket_task_created_40c8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='ticket_task_priorit_72a639_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='ticket_task_due_dat_e58ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['ticket', '-created_at'], name='ticket_acti_ticket__fae697_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['activity_type'], name='ticket_acti_activit_0ef9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='activitystream',
            index=models.Index(fields=['actor'], name='ticket_acti_actor_i_000c88_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', '-created_at'], name='ticket_tick_ticket__c6d354_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['author'], name='ticket_tick_author__646a84_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['ticket', 'status'], name='ticket_work_ticket__40dc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assignee'], name='ticket_work_assigne_60a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['due_date'], name='ticket_work_due_dat_efa9e9_idx'),
        ),
    ]
