# Generated by Django 5.0.2 on 2026-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticketattachment_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('web', 'Web/Portal'), ('phone', 'Phone'), ('chat', 'Live Chat'), ('chatbot', 'AI Chatbot'), ('api', 'API/Integrations'), ('internal', 'Internal/Staff-created'), ('customer_portal', 'Customer Portal'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='web', help_text='How the ticket was created', max_length=20, null=True),
        ),
    ]
