# Generated by Django 5.0.2 on 2026-03-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was merged', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Parent ticket this ticket was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='activitystream',
            name='activity_type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('watcher_added', 'Watcher Added'), ('watcher_removed', 'Watcher Removed'), ('department_changed', 'Department Changed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('workitem_added', 'Work Item Added'), ('workitem_updated', 'Work Item Updated'), ('workitem_status_changed', 'Work Item Status Changed'), ('workitem_completed', 'Work Item Completed'), ('ticket_merged', 'Ticket Merged')], max_length=30),
        ),
    ]
