# Generated by Django 5.0.2 on 2026-03-11 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_add_merge_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned in this comment', related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
