# Generated by Django 5.0.2 on 2026-03-12 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('template_type', models.CharField(choices=[('invitation', 'Survey Invitation'), ('reminder', 'Survey Reminder'), ('thank_you', 'Thank You / Confirmation')], default='invitation', max_length=20)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('body_html', models.TextField(help_text='HTML email body')),
                ('body_text', models.TextField(blank=True, help_text='Plain text email body (fallback)')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable surveys globally')),
                ('default_send_delay', models.IntegerField(default=30, help_text='Default delay before sending survey (in minutes)', validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_anonymous_responses', models.BooleanField(default=False, help_text='Allow users to submit anonymous responses')),
                ('response_expiry_days', models.IntegerField(default=7, help_text='Number of days before survey link expires', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('default_rating_scale', models.IntegerField(choices=[(5, '1-5 Scale'), (10, '1-10 Scale')], default=5, help_text='Default rating scale for CSAT questions')),
                ('send_reminders', models.BooleanField(default=True, help_text='Send reminder emails for incomplete surveys')),
                ('reminder_days', models.IntegerField(default=3, help_text='Days after initial email to send reminder', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_reminders', models.IntegerField(default=1, help_text='Maximum number of reminders to send', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Survey Settings',
                'verbose_name_plural': 'Survey Settings',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Survey name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Survey description shown to respondents')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not shown to respondents)')),
                ('survey_type', models.CharField(choices=[('csat', 'Customer Satisfaction (CSAT)'), ('resolution', 'Resolution Quality'), ('agent', 'Agent Performance'), ('nps', 'Net Promoter Score (NPS)'), ('custom', 'Custom Survey')], default='csat', help_text='Type of survey', max_length=20)),
                ('trigger_event', models.CharField(choices=[('resolved', 'After Ticket Resolved'), ('closed', 'After Ticket Closed'), ('sla_breach', 'After SLA Breach'), ('manual', 'Manual Trigger')], default='resolved', help_text='Event that triggers the survey', max_length=20)),
                ('send_delay', models.IntegerField(default=30, help_text='Delay before sending survey (in minutes)', validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_days', models.IntegerField(default=7, help_text='Number of days the survey link remains valid', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Survey is active and can be sent')),
                ('allow_multiple_responses', models.BooleanField(default=False, help_text='Allow multiple responses from same user per ticket')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Allow anonymous responses')),
                ('thank_you_message', models.TextField(default='Thank you for your feedback! Your response helps us improve our service.', help_text='Message shown after survey completion')),
                ('is_default', models.BooleanField(default=False, help_text='Default survey for this trigger event')),
                ('target_priorities', models.JSONField(blank=True, default=list, help_text='Only trigger for tickets with these priorities (empty = all)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('target_departments', models.ManyToManyField(blank=True, help_text='Only trigger for tickets in these departments (empty = all)', related_name='surveys', to='ticket.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of invitations that got responses', max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of responses that were completed', max_digits=5)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nps_score', models.DecimalField(blank=True, decimal_places=2, help_text='Net Promoter Score (-100 to 100)', max_digits=5, null=True)),
                ('csat_score', models.DecimalField(blank=True, decimal_places=2, help_text='Customer Satisfaction Score (percentage)', max_digits=5, null=True)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.survey')),
            ],
            options={
                'verbose_name_plural': 'Survey Analytics',
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email address to send survey invitation', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='Name of the recipient', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending (Queued)'), ('sent', 'Sent'), ('opened', 'Opened'), ('completed', 'Completed'), ('expired', 'Expired'), ('bounced', 'Email Bounced')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='When the survey should be sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When the survey link expires')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (ticket info, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_invitations_as_agent', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_invitations', to='ticket.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question to ask')),
                ('question_type', models.CharField(choices=[('rating', 'Rating (Stars/Numeric)'), ('single_choice', 'Single Choice (Radio)'), ('multiple_choice', 'Multiple Choice (Checkbox)'), ('text', 'Free Text'), ('yes_no', 'Yes / No'), ('nps', 'NPS (0-10 Scale)')], default='rating', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Response is required')),
                ('rating_scale', models.IntegerField(default=5, help_text='Maximum value for rating scale', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('rating_labels', models.JSONField(blank=True, default=dict, help_text="Custom labels for rating values, e.g., {'1': 'Poor', '5': 'Excellent'}")),
                ('min_length', models.IntegerField(default=0, help_text='Minimum text length (0 = no minimum)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_length', models.IntegerField(default=2000, help_text='Maximum text length', validators=[django.core.validators.MinValueValidator(1)])),
                ('placeholder_text', models.CharField(blank=True, help_text='Placeholder text for text input', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditional_value', models.CharField(blank=True, help_text='Show only when conditional question has this value', max_length=255)),
                ('conditional_question', models.ForeignKey(blank=True, help_text='Only show if this question has a specific answer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Choice label shown to user', max_length=255)),
                ('value', models.CharField(help_text='Value stored in response', max_length=255)),
                ('is_other', models.BooleanField(default=False, help_text="This is an 'Other' option that allows text input")),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Computed average rating from all rating questions', max_digits=4, null=True)),
                ('nps_score', models.IntegerField(blank=True, help_text='NPS score if survey contains NPS question', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='Overall sentiment based on responses', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses_as_agent', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='surveys.surveyinvitation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='ticket.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, help_text='Text answer')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric/rating answer', max_digits=5, null=True)),
                ('choice_values', models.JSONField(blank=True, default=list, help_text='Selected choice values for single/multiple choice')),
                ('boolean_value', models.BooleanField(blank=True, help_text='Yes/No answer', null=True)),
                ('other_text', models.TextField(blank=True, help_text="Text for 'Other' option")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'trigger_event'], name='surveys_sur_is_acti_5da6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['survey_type'], name='surveys_sur_survey__5c4359_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyinvitation',
            index=models.Index(fields=['status', 'scheduled_at'], name='surveys_sur_status_881f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyinvitation',
            index=models.Index(fields=['token'], name='surveys_sur_token_5f7f70_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyinvitation',
            index=models.Index(fields=['ticket', 'survey'], name='surveys_sur_ticket__bd6ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyinvitation',
            index=models.Index(fields=['email'], name='surveys_sur_email_e9edae_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'order'], name='surveys_sur_survey__f6f6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', '-submitted_at'], name='surveys_sur_survey__5757f3_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['ticket'], name='surveys_sur_ticket__11bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['agent'], name='surveys_sur_agent_i_7e27c9_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['sentiment'], name='surveys_sur_sentime_d63b98_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['overall_rating'], name='surveys_sur_overall_d724ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('response', 'question')},
        ),
    ]
