# Generated by Django 5.0.2 on 2026-02-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authenticator_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Authenticator app 2FA is enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_2fa_code',
            field=models.CharField(blank=True, help_text='Temporary email verification code', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_2fa_code_expires',
            field=models.DateTimeField(blank=True, help_text='Email code expiration time', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Email-based 2FA is enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for authenticator app', max_length=64),
        ),
    ]
