# Generated by Django 5.0.2 on 2026-02-16 10:10

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_type', models.CharField(blank=True, help_text='Type of business (e.g., Software, Insurance, Healthcare)', max_length=100, null=True)),
                ('org_size', models.CharField(blank=True, help_text='Organization size range', max_length=50, null=True)),
                ('service_types', models.JSONField(blank=True, help_text='Types of services looking for', null=True)),
                ('features_interest', models.JSONField(blank=True, help_text='Features user wants to explore', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='shared.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
