# Generated by Django 5.0.2 on 2026-03-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the account email has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the account was verified', null=True)),
                ('business_type', models.CharField(blank=True, help_text='Type of business (e.g., Software, Insurance, Healthcare)', max_length=100, null=True)),
                ('org_size', models.CharField(blank=True, help_text='Organization size range', max_length=50, null=True)),
                ('service_types', models.JSONField(blank=True, help_text='Types of services looking for', null=True)),
                ('features_interest', models.JSONField(blank=True, help_text='Features user wants to explore', null=True)),
                ('created_by_email', models.EmailField(blank=True, help_text='Email of the admin who registered this business', max_length=254, null=True)),
                ('created_by_name', models.CharField(blank=True, help_text='Name of the admin who registered this business', max_length=200, null=True)),
                ('registration_ip', models.GenericIPAddressField(blank=True, help_text='IP address during registration', null=True)),
                ('registration_country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100, null=True)),
                ('registration_city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, null=True)),
                ('registration_region', models.CharField(blank=True, help_text='Region/State from IP geolocation', max_length=100, null=True)),
                ('registration_timezone', models.CharField(blank=True, help_text='Timezone from IP geolocation', max_length=100, null=True)),
                ('registration_location_data', models.JSONField(blank=True, help_text='Full geolocation data', null=True)),
                ('registration_user_agent', models.TextField(blank=True, help_text='Browser/device user agent string', null=True)),
                ('registration_timestamp', models.DateTimeField(blank=True, help_text='Exact registration timestamp', null=True)),
                ('slack_integration_status', models.CharField(default='not_connected', help_text='Status of Slack integration', max_length=50)),
                ('slack_workspace_info', models.JSONField(blank=True, help_text='Slack workspace information', null=True)),
                ('slack_app_credentials', models.JSONField(blank=True, help_text='Slack app credentials', null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='shared.client')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='TenantVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the verification token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('registration_data', models.JSONField(help_text='Registration data to be processed after verification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='shared.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
