# Generated by Django 5.0.2 on 2026-02-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slack_app_credentials',
            field=models.JSONField(blank=True, help_text='Slack app credentials', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='slack_integration_status',
            field=models.CharField(default='not_connected', help_text='Status of Slack integration', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='slack_workspace_info',
            field=models.JSONField(blank=True, help_text='Slack workspace information', null=True),
        ),
    ]
