# Generated by Django 5.0.2 on 2026-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_add_slack_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='Email of the admin who registered this business', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of the admin who registered this business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_city',
            field=models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_country',
            field=models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address during registration', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_location_data',
            field=models.JSONField(blank=True, help_text='Full geolocation data', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_region',
            field=models.CharField(blank=True, help_text='Region/State from IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_timestamp',
            field=models.DateTimeField(blank=True, help_text='Exact registration timestamp', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_timezone',
            field=models.CharField(blank=True, help_text='Timezone from IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_user_agent',
            field=models.TextField(blank=True, help_text='Browser/device user agent string', null=True),
        ),
    ]
