# Generated by Django 5.0.2 on 2026-03-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_client_created_by_email_client_created_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the account email has been verified'),
        ),
        migrations.AddField(
            model_name='client',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the account was verified', null=True),
        ),
        migrations.CreateModel(
            name='TenantVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the verification token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('registration_data', models.JSONField(help_text='Registration data to be processed after verification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='shared.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
