# Generated by Django 5.0.2 on 2026-02-16 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Business Hours', max_length=200)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for business hours', max_length=100)),
                ('monday_enabled', models.BooleanField(default=True)),
                ('monday_start', models.TimeField(default='09:00:00')),
                ('monday_end', models.TimeField(default='17:00:00')),
                ('tuesday_enabled', models.BooleanField(default=True)),
                ('tuesday_start', models.TimeField(default='09:00:00')),
                ('tuesday_end', models.TimeField(default='17:00:00')),
                ('wednesday_enabled', models.BooleanField(default=True)),
                ('wednesday_start', models.TimeField(default='09:00:00')),
                ('wednesday_end', models.TimeField(default='17:00:00')),
                ('thursday_enabled', models.BooleanField(default=True)),
                ('thursday_start', models.TimeField(default='09:00:00')),
                ('thursday_end', models.TimeField(default='17:00:00')),
                ('friday_enabled', models.BooleanField(default=True)),
                ('friday_start', models.TimeField(default='09:00:00')),
                ('friday_end', models.TimeField(default='17:00:00')),
                ('saturday_enabled', models.BooleanField(default=False)),
                ('saturday_start', models.TimeField(default='09:00:00')),
                ('saturday_end', models.TimeField(default='17:00:00')),
                ('sunday_enabled', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(default='09:00:00')),
                ('sunday_end', models.TimeField(default='17:00:00')),
                ('pause_outside_hours', models.BooleanField(default=True, help_text='Pause SLA timer outside business hours')),
                ('exclude_holidays', models.BooleanField(default=True, help_text='Exclude holidays from SLA calculations')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the active business hours configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name', max_length=200)),
                ('date', models.DateField(help_text='Holiday date')),
                ('recurring', models.BooleanField(default=True, help_text='Does this holiday recur annually?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy name (e.g., Critical Priority SLA)', max_length=200)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Ticket priority this policy applies to', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Policy description')),
                ('first_response_time', models.IntegerField(help_text='Target time for first response (in minutes)', validators=[django.core.validators.MinValueValidator(1)])),
                ('resolution_time', models.IntegerField(help_text='Target time for ticket resolution (in minutes)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('apply_business_hours', models.BooleanField(default=True, help_text='Only count time during business hours')),
                ('apply_holidays', models.BooleanField(default=False, help_text='Exclude holidays from SLA time calculation')),
                ('apply_to_new_tickets', models.BooleanField(default=False, help_text='Automatically apply this policy to new tickets matching the priority')),
                ('send_escalation_emails', models.BooleanField(default=False, help_text='Send email notifications when SLA is at risk of breach')),
                ('pause_on_pending', models.BooleanField(default=False, help_text='Pause SLA timer when ticket status is pending')),
                ('notify_before_breach', models.IntegerField(default=30, help_text='Send notification X minutes before SLA breach (0 to disable)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='SLASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable SLA tracking globally')),
                ('auto_pause_resolved', models.BooleanField(default=True, help_text='Automatically pause SLA when ticket is resolved')),
                ('auto_resume_reopened', models.BooleanField(default=True, help_text='Automatically resume SLA when ticket is reopened')),
                ('escalation_enabled', models.BooleanField(default=True, help_text='Enable automatic escalation when SLA is breached')),
                ('send_notifications', models.BooleanField(default=True, help_text='Send notifications for SLA warnings and breaches')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SLA Settings',
                'verbose_name_plural': 'SLA Settings',
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_due_at', models.DateTimeField(blank=True, help_text='When first response is due', null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, help_text='When ticket resolution is due', null=True)),
                ('response_breached', models.BooleanField(default=False, help_text='Has first response SLA been breached?')),
                ('resolution_breached', models.BooleanField(default=False, help_text='Has resolution SLA been breached?')),
                ('is_on_hold', models.BooleanField(default=False, help_text='Is the SLA timer currently on hold?')),
                ('hold_reason', models.TextField(blank=True, help_text='Reason for putting SLA on hold')),
                ('hold_started_at', models.DateTimeField(blank=True, help_text='When the hold was started', null=True)),
                ('total_hold_time', models.IntegerField(default=0, help_text='Total time in minutes that SLA has been on hold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='SLA policy applied to this ticket', on_delete=django.db.models.deletion.PROTECT, to='sla.slapolicy')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Ticket SLA',
                'verbose_name_plural': 'Ticket SLAs',
                'indexes': [models.Index(fields=['policy'], name='sla_tickets_policy__67c3cf_idx'), models.Index(fields=['response_due_at'], name='sla_tickets_respons_36714b_idx'), models.Index(fields=['resolution_due_at'], name='sla_tickets_resolut_9212c3_idx')],
            },
        ),
    ]
