# Generated by Django 5.0.2 on 2026-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsla',
            name='breach_warning_sent_resolution',
            field=models.BooleanField(default=False, help_text='Has breach warning been sent for resolution SLA?'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='breach_warning_sent_response',
            field=models.BooleanField(default=False, help_text='Has breach warning been sent for first response SLA?'),
        ),
    ]
