# Generated by Django 5.0.2 on 2026-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_add_breach_warning_sent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='auto_assign_on_breach',
            field=models.BooleanField(default=False, help_text='Automatically assign ticket to an administrator when SLA is breached'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='auto_assigned_on_breach',
            field=models.BooleanField(default=False, help_text='Was ticket auto-assigned due to breach?'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='breach_email_sent',
            field=models.BooleanField(default=False, help_text='Has SLA breached email been sent?'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='escalation_email_sent',
            field=models.BooleanField(default=False, help_text='Has escalation email been sent?'),
        ),
    ]
