# Generated by Django 5.0.2 on 2026-03-12 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(help_text='Short description')),
                ('long_description', models.TextField(help_text='Detailed description with features')),
                ('icon', models.CharField(default='puzzle', help_text='Icon name or emoji', max_length=50)),
                ('category', models.CharField(choices=[('automation', 'Automation'), ('communication', 'Communication'), ('productivity', 'Productivity'), ('asset', 'Asset Management'), ('reporting', 'Reporting & Analytics'), ('integration', 'Integration'), ('other', 'Other')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD', max_digits=10)),
                ('is_free', models.BooleanField(default=False, help_text='Is this app free?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('beta', 'Beta'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured apps')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('developer', models.CharField(default='ImaraDesk', max_length=200)),
                ('install_count', models.IntegerField(default=0, help_text='Number of installations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'db_table': 'setting_apps',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('template_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_updated', 'Ticket Updated'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_priority_changed', 'Ticket Priority Changed'), ('ticket_merged', 'Ticket Merged'), ('new_activity_notice', 'New Activity Notice'), ('new_message_auto_response', 'Message Auto Response'), ('new_ticket_notice', 'New Ticket Notice (Agent)'), ('response_reply_template', 'Agent Response Reply'), ('internal_activity_alert', 'Internal Activity Alert'), ('new_message_alert', 'New Message Alert (Agent)'), ('overdue_ticket_alert', 'Overdue Ticket Alert'), ('ticket_transfer_alert', 'Ticket Transfer Alert'), ('task_new_activity_alert', 'Task Activity Alert (Agent)'), ('task_new_activity_notice', 'Task Activity Notice (User)'), ('new_task_alert', 'New Task Alert'), ('overdue_task_alert', 'Overdue Task Alert'), ('task_assignment_alert', 'Task Assignment Alert'), ('task_transfer_alert', 'Task Transfer Alert'), ('sla_reminder', 'SLA Reminder'), ('sla_escalation_notice_task', 'SLA Escalation Notice (Task)'), ('sla_escalation_notice', 'SLA Escalation Notice (Ticket)'), ('sla_first_response_breach', 'First Response SLA Breach'), ('sla_resolution_breach', 'Resolution SLA Breach'), ('sla_resolved_notice', 'Ticket Resolved Within SLA'), ('sla_breach_warning', 'SLA Breach Warning'), ('sla_breached', 'SLA Breached'), ('comment_add_notice', 'Comment Added Notice'), ('comment_reply_notice', 'Comment Reply Notice'), ('user_mentioned', 'User Mentioned in Ticket'), ('welcome_user', 'Welcome Email'), ('password_reset', 'Password Reset'), ('weekly_report', 'Weekly Report'), ('custom', 'Custom Template')], help_text='Template type', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject with placeholders like {{ticket_number}}', max_length=500)),
                ('body_html', models.TextField(help_text='HTML email body with placeholders')),
                ('body_text', models.TextField(blank=True, help_text='Plain text fallback')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('available_variables', models.JSONField(default=dict, help_text="Available variables like {'ticket_number': 'Ticket number', 'user_name': 'User name'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'setting_email_templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_access', models.BooleanField(default=True, help_text='Allow unauthenticated users to view published articles')),
                ('require_login_to_view', models.BooleanField(default=False, help_text='Require users to login to view any articles')),
                ('allow_article_rating', models.BooleanField(default=True, help_text='Allow users to rate articles as helpful/not helpful')),
                ('allow_article_comments', models.BooleanField(default=True, help_text='Allow users to comment on articles')),
                ('require_approval', models.BooleanField(default=True, help_text='Require approval before articles are published')),
                ('auto_publish_on_approval', models.BooleanField(default=True, help_text='Automatically publish articles when approved')),
                ('notify_approvers', models.BooleanField(default=True, help_text='Send email notifications to approvers')),
                ('notify_author_on_approval', models.BooleanField(default=True, help_text='Notify author when article is approved')),
                ('notify_author_on_rejection', models.BooleanField(default=True, help_text='Notify author when article is rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Settings',
                'verbose_name_plural': 'Knowledge Base Settings',
                'db_table': 'setting_kb',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_ticket_created', models.BooleanField(default=True, help_text='When a new ticket is submitted')),
                ('notify_ticket_assigned', models.BooleanField(default=True, help_text='When a ticket is assigned')),
                ('notify_ticket_status_changed', models.BooleanField(default=True, help_text='When ticket status is updated (open, pending, resolved, closed)')),
                ('notify_ticket_priority_changed', models.BooleanField(default=True, help_text='When ticket priority is updated (low, medium, high, urgent)')),
                ('notify_new_comment', models.BooleanField(default=True, help_text='When someone comments on a ticket')),
                ('notify_ticket_reassigned', models.BooleanField(default=False, help_text='When a ticket is reassigned to another agent')),
                ('notify_ticket_group_assigned', models.BooleanField(default=True, help_text='When a ticket is assigned to a group (notifies all group members)')),
                ('notify_ticket_merged', models.BooleanField(default=True, help_text='When tickets are merged together')),
                ('notify_ticket_mentioned', models.BooleanField(default=True, help_text='When someone is mentioned using @username in a ticket')),
                ('weekly_performance_report', models.BooleanField(default=False, help_text='Send weekly summary of team performance and metrics')),
                ('weekly_report_email', models.EmailField(blank=True, help_text='Email address to receive weekly reports', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'setting_notifications',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_2fa', models.BooleanField(default=True, help_text='Allow email-based two-factor authentication')),
                ('enable_authenticator_2fa', models.BooleanField(default=True, help_text='Allow authenticator app (TOTP) two-factor authentication')),
                ('require_2fa_for_admins', models.BooleanField(default=False, help_text='Require 2FA for all admin users')),
                ('require_2fa_for_all_users', models.BooleanField(default=False, help_text='Require 2FA for all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
                'db_table': 'setting_security_config',
            },
        ),
        migrations.CreateModel(
            name='SettingsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TICKET', 'Ticket'), ('TASK', 'Task'), ('KB', 'Knowledge Base')], db_index=True, help_text='Type of view (Ticket, Task, or KB)', max_length=10)),
                ('view_id', models.CharField(help_text="Unique identifier for the view (e.g., 'all_tickets', 'my_tasks')", max_length=100)),
                ('label', models.CharField(help_text='Display label for the view', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this view displays', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this view is enabled and visible to users')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default view to show')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings View',
                'verbose_name_plural': 'Settings Views',
                'db_table': 'setting_view',
                'ordering': ['type', 'order', 'label'],
                'unique_together': {('type', 'view_id')},
            },
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_installed_at', models.DateTimeField(auto_now_add=True, help_text='Original installation date - never changes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the app currently active?')),
                ('uninstalled_at', models.DateTimeField(blank=True, help_text='When the app was uninstalled', null=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='settings.app')),
            ],
            options={
                'verbose_name': 'Installed App',
                'verbose_name_plural': 'Installed Apps',
                'db_table': 'setting_installed_apps',
                'unique_together': {('app',)},
            },
        ),
    ]
