# Generated by Django 5.0.2 on 2026-03-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDomain',
        ),
        migrations.RemoveField(
            model_name='telegramintegration',
            name='app',
        ),
        migrations.RemoveField(
            model_name='slackintegration',
            name='app',
        ),
        migrations.RemoveField(
            model_name='teamsintegration',
            name='app',
        ),
        migrations.DeleteModel(
            name='SMTP',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramIntegration',
        ),
        migrations.DeleteModel(
            name='SlackIntegration',
        ),
        migrations.DeleteModel(
            name='SettingsIntegrations',
        ),
        migrations.DeleteModel(
            name='TeamsIntegration',
        ),
        migrations.DeleteModel(
            name='TelegramChat',
        ),
    ]
