# Generated by Django 5.0.2 on 2026-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settingsintegrations',
            table='setting_integrations_12',
        ),
    ]
