# Generated by Django 5.0.2 on 2026-02-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settingsintegrations_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settingsintegrations',
            table='setting_integrations',
        ),
    ]
