# Generated by Django 5.0.2 on 2026-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_settingsintegrations_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(help_text='Slack workspace/team ID', max_length=50, unique=True)),
                ('team_name', models.CharField(help_text='Slack workspace name', max_length=255)),
                ('access_token', models.TextField(help_text='Bot access token (xoxb-...)')),
                ('bot_user_id', models.CharField(blank=True, help_text='Bot user ID', max_length=50, null=True)),
                ('authed_user_id', models.CharField(blank=True, help_text='ID of user who authorized the app', max_length=50, null=True)),
                ('scope', models.TextField(blank=True, help_text='Comma-separated list of granted scopes', null=True)),
                ('default_channel_id', models.CharField(blank=True, help_text='Default channel for notifications', max_length=50, null=True)),
                ('default_channel_name', models.CharField(blank=True, help_text='Name of default channel', max_length=255, null=True)),
                ('notify_new_ticket', models.BooleanField(default=True, help_text='Send notification when new ticket is created')),
                ('notify_ticket_assigned', models.BooleanField(default=True, help_text='Send notification when ticket is assigned')),
                ('notify_ticket_resolved', models.BooleanField(default=True, help_text='Send notification when ticket is resolved')),
                ('notify_sla_breach', models.BooleanField(default=True, help_text='Send notification on SLA breach')),
                ('notify_new_comment', models.BooleanField(default=False, help_text='Send notification on new comments')),
                ('is_active', models.BooleanField(default=True, help_text='Is integration active')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a message was sent', null=True)),
            ],
            options={
                'verbose_name': 'Slack Integration',
                'verbose_name_plural': 'Slack Integrations',
                'db_table': 'setting_slack_integration',
            },
        ),
    ]
