# Generated by Django 5.0.2 on 2026-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_add_slack_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Azure AD tenant ID', max_length=100, unique=True)),
                ('tenant_name', models.CharField(blank=True, help_text='Organization name from Azure AD', max_length=255, null=True)),
                ('access_token', models.TextField(help_text='Microsoft Graph API access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token for token renewal', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('authed_user_id', models.CharField(blank=True, help_text='Azure AD user ID who authorized the app', max_length=100, null=True)),
                ('authed_user_email', models.EmailField(blank=True, help_text='Email of user who authorized', max_length=254, null=True)),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of granted scopes', null=True)),
                ('default_team_id', models.CharField(blank=True, help_text='Default Teams team ID for notifications', max_length=100, null=True)),
                ('default_team_name', models.CharField(blank=True, help_text='Name of default team', max_length=255, null=True)),
                ('default_channel_id', models.CharField(blank=True, help_text='Default channel ID for notifications', max_length=100, null=True)),
                ('default_channel_name', models.CharField(blank=True, help_text='Name of default channel', max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Teams incoming webhook URL', null=True)),
                ('notify_new_ticket', models.BooleanField(default=True, help_text='Send notification when new ticket is created')),
                ('notify_ticket_assigned', models.BooleanField(default=True, help_text='Send notification when ticket is assigned')),
                ('notify_ticket_resolved', models.BooleanField(default=True, help_text='Send notification when ticket is resolved')),
                ('notify_sla_breach', models.BooleanField(default=True, help_text='Send notification on SLA breach')),
                ('notify_new_comment', models.BooleanField(default=False, help_text='Send notification on new comments')),
                ('is_active', models.BooleanField(default=True, help_text='Is integration active')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a message was sent', null=True)),
            ],
            options={
                'verbose_name': 'Teams Integration',
                'verbose_name_plural': 'Teams Integrations',
                'db_table': 'setting_teams_integration',
            },
        ),
    ]
