# Generated by Django 5.0.2 on 2026-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_add_teams_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsintegrations',
            name='is_integrated',
            field=models.BooleanField(blank=True, default=False, help_text='Is integration connected/functional', null=True),
        ),
    ]
