# Generated by Django 5.0.2 on 2026-02-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settingsintegrations_is_integrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackintegration',
            name='app',
            field=models.ForeignKey(blank=True, help_text='Reference to the integration app entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_connections', to='settings.settingsintegrations'),
        ),
        migrations.AddField(
            model_name='teamsintegration',
            name='app',
            field=models.ForeignKey(blank=True, help_text='Reference to the integration app entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_connections', to='settings.settingsintegrations'),
        ),
    ]
