# Generated by Django 5.0.2 on 2026-02-19 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_add_app_fk_to_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='first_installed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Original installation date - never changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installedapp',
            name='uninstalled_at',
            field=models.DateTimeField(blank=True, help_text='When the app was uninstalled', null=True),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
    ]
