# Generated by Django 5.0.2 on 2026-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_add_trial_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapp',
            name='first_installed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Original installation date - never changes', null=True),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='installed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
