# Generated by Django 5.0.2 on 2026-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_installedapp_first_installed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Custom domain (e.g., support.example.com)', max_length=255, unique=True)),
                ('purpose', models.CharField(choices=[('helpdesk', 'Helpdesk'), ('knowledge_base', 'Knowledge Base'), ('customer_portal', 'Customer Portal'), ('all', 'All Services')], default='all', help_text='Service this domain is used for', max_length=20)),
                ('verification_token', models.CharField(blank=True, help_text='DNS TXT record verification token', max_length=64)),
                ('dns_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('dns_verified_at', models.DateTimeField(blank=True, help_text='When DNS was verified', null=True)),
                ('dns_last_checked_at', models.DateTimeField(blank=True, help_text='Last DNS check timestamp', null=True)),
                ('dns_error_message', models.TextField(blank=True, help_text='DNS verification error message')),
                ('required_cname_record', models.CharField(blank=True, help_text='CNAME record target', max_length=255)),
                ('required_txt_record', models.CharField(blank=True, help_text='TXT record value for verification', max_length=512)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ssl_issued_at', models.DateTimeField(blank=True, help_text='SSL certificate issue date', null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, help_text='SSL certificate expiry date', null=True)),
                ('ssl_certificate_path', models.CharField(blank=True, help_text='Path to SSL certificate file', max_length=500)),
                ('ssl_private_key_path', models.CharField(blank=True, help_text='Path to SSL private key file', max_length=500)),
                ('ssl_error_message', models.TextField(blank=True, help_text='SSL provisioning error message')),
                ('is_active', models.BooleanField(default=True, help_text='Is this domain active')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary custom domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'db_table': 'setting_custom_domains',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
