# Generated by Django 5.0.2 on 2026-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='ssl_provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare Origin Certificate'), ('letsencrypt', "Let's Encrypt"), ('manual', 'Manual Certificate')], default='cloudflare', help_text='SSL certificate provider', max_length=20),
        ),
    ]
