# Generated by Django 5.0.2 on 2026-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_add_ssl_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='cloudflare_hostname_id',
            field=models.CharField(blank=True, help_text='Cloudflare custom hostname ID', max_length=64),
        ),
    ]
