# Generated by Django 5.0.2 on 2026-03-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_remove_securitysettings_account_lockout_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasesettings',
            name='kb_enabled',
        ),
        migrations.RemoveField(
            model_name='knowledgebasesettings',
            name='notify_on_comment',
        ),
        migrations.RemoveField(
            model_name='knowledgebasesettings',
            name='notify_on_rating',
        ),
    ]
