# Generated by Django 5.0.2 on 2026-03-10 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_remove_kb_settings_fields'),
        ('ticket', '0005_alter_ticket_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot Token from @BotFather', max_length=255)),
                ('bot_username', models.CharField(blank=True, help_text='Bot username (without @)', max_length=100, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for receiving messages', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret token for webhook validation', max_length=255, null=True)),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from new conversations')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from Telegram', max_length=20)),
                ('welcome_message', models.TextField(blank=True, default='Hello! Welcome to our support. Send a message to create a support ticket.', help_text='Message sent when a new user starts a conversation')),
                ('notify_new_ticket', models.BooleanField(default=True, help_text='Send notification when new ticket is created')),
                ('notify_ticket_resolved', models.BooleanField(default=True, help_text='Send notification when ticket is resolved')),
                ('notify_new_comment', models.BooleanField(default=True, help_text='Send notification on new comments/replies')),
                ('is_active', models.BooleanField(default=True, help_text='Is integration active')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a message was processed', null=True)),
                ('app', models.ForeignKey(blank=True, help_text='Reference to the integration app entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_connections', to='settings.settingsintegrations')),
            ],
            options={
                'verbose_name': 'Telegram Integration',
                'verbose_name_plural': 'Telegram Integrations',
                'db_table': 'setting_telegram_integration',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram chat ID', unique=True)),
                ('username', models.CharField(blank=True, help_text='Telegram username', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=100, null=True)),
                ('last_message_id', models.BigIntegerField(blank=True, help_text='Last processed message ID', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this chat active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(blank=True, help_text='Associated ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chats', to='ticket.ticket')),
                ('user', models.ForeignKey(blank=True, help_text='Linked system user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Chat',
                'verbose_name_plural': 'Telegram Chats',
                'db_table': 'setting_telegram_chat',
                'indexes': [models.Index(fields=['chat_id'], name='setting_tel_chat_id_e3a4c8_idx'), models.Index(fields=['ticket'], name='setting_tel_ticket__de7444_idx')],
            },
        ),
    ]
