# Generated by Django 5.0.2 on 2026-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_telegramintegration_telegramchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsintegrations',
            name='icon',
            field=models.CharField(help_text="Lucide React icon name (e.g., 'MessageSquare', 'Mail')", max_length=50),
        ),
    ]
