# Generated by Django 5.0.2 on 2026-03-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_update_icon_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_ticket_created', models.BooleanField(default=True, help_text='When a new ticket is submitted')),
                ('notify_ticket_assigned', models.BooleanField(default=True, help_text='When a ticket is assigned')),
                ('notify_ticket_status_changed', models.BooleanField(default=True, help_text='When ticket status is updated (open, pending, resolved, closed)')),
                ('notify_ticket_priority_changed', models.BooleanField(default=True, help_text='When ticket priority is updated (low, medium, high, urgent)')),
                ('notify_new_comment', models.BooleanField(default=True, help_text='When someone comments on a ticket')),
                ('notify_ticket_reassigned', models.BooleanField(default=False, help_text='When a ticket is reassigned to another agent')),
                ('notify_ticket_merged', models.BooleanField(default=True, help_text='When tickets are merged together')),
                ('notify_ticket_mentioned', models.BooleanField(default=True, help_text='When someone is mentioned using @username in a ticket')),
                ('weekly_performance_report', models.BooleanField(default=False, help_text='Send weekly summary of team performance and metrics')),
                ('weekly_report_email', models.EmailField(blank=True, help_text='Email address to receive weekly reports', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'setting_notifications',
            },
        ),
    ]
