# Generated by Django 5.0.2 on 2026-02-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0002_add_slack_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='The Message-ID header from the email', max_length=255, unique=True)),
                ('from_address', models.EmailField(help_text='Sender email address', max_length=254)),
                ('to_address', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(help_text='When the email was received')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_created', models.BooleanField(default=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this email was processed for', on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='shared.client')),
            ],
            options={
                'verbose_name': 'Processed Email',
                'verbose_name_plural': 'Processed Emails',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantHelpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='The help email address for this tenant (e.g., help+tenant@coredesk.pro)', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this help email is active and should process incoming emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=True, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('tenant', models.OneToOneField(help_text='The tenant this help email belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='help_email', to='shared.client')),
            ],
            options={
                'verbose_name': 'Tenant Help Email',
                'verbose_name_plural': 'Tenant Help Emails',
                'ordering': ['tenant__name'],
            },
        ),
    ]
