# Generated by Django 5.0.2 on 2026-03-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIMAPMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address for this mailbox', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name for this mailbox', max_length=255)),
                ('imap_host', models.CharField(help_text='IMAP server hostname (e.g., imap.gmail.com)', max_length=255)),
                ('imap_port', models.IntegerField(default=993, help_text='IMAP server port (993 for SSL, 143 for non-SSL)')),
                ('imap_use_ssl', models.BooleanField(default=True, help_text='Use SSL/TLS for IMAP connection')),
                ('enable_smtp', models.BooleanField(default=False, help_text='Enable outgoing email (SMTP) for this mailbox')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL, 25 for non-secure)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP connection')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP connection')),
                ('username', models.CharField(help_text='Username for authentication (usually email address)', max_length=255)),
                ('password', models.CharField(help_text='Password or app-specific password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mailbox should be processed for tickets')),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=False, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('folder_to_watch', models.CharField(default='INBOX', help_text='Mail folder to watch for new emails (e.g., INBOX)', max_length=100)),
                ('mark_as_read', models.BooleanField(default=True, help_text='Mark emails as read after processing')),
                ('move_to_folder', models.CharField(blank=True, help_text='Optionally move processed emails to this folder', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time emails were fetched from this mailbox', null=True)),
            ],
            options={
                'verbose_name': 'Custom IMAP Mailbox',
                'verbose_name_plural': 'Custom IMAP Mailboxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutlookMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='The Outlook mailbox email address', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the mailbox owner', max_length=255)),
                ('mailbox_id', models.CharField(blank=True, help_text='Microsoft Graph user/mailbox ID', max_length=255)),
                ('access_token', models.TextField(help_text='Microsoft Graph API access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token for token renewal', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of granted scopes', null=True)),
                ('azure_tenant_id', models.CharField(blank=True, help_text='Azure AD tenant ID', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mailbox should be processed for tickets')),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=False, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('folder_to_watch', models.CharField(default='Inbox', help_text='Mail folder to watch for new emails (e.g., Inbox)', max_length=100)),
                ('mark_as_read', models.BooleanField(default=True, help_text='Mark emails as read after processing')),
                ('move_to_folder', models.CharField(blank=True, help_text='Optionally move processed emails to this folder', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time emails were fetched from this mailbox', null=True)),
            ],
            options={
                'verbose_name': 'Outlook Mailbox',
                'verbose_name_plural': 'Outlook Mailboxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='The Message-ID header from the email', max_length=255, unique=True)),
                ('from_address', models.EmailField(help_text='Sender email address', max_length=254)),
                ('to_address', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(help_text='When the email was received')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_created', models.BooleanField(default=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this email was processed for', on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='shared.client')),
            ],
            options={
                'verbose_name': 'Processed Email',
                'verbose_name_plural': 'Processed Emails',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantHelpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='The help email address for this tenant (e.g., help+tenant@coredesk.pro)', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this help email is active and should process incoming emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=True, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('tenant', models.OneToOneField(help_text='The tenant this help email belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='help_email', to='shared.client')),
            ],
            options={
                'verbose_name': 'Tenant Help Email',
                'verbose_name_plural': 'Tenant Help Emails',
                'ordering': ['tenant__name'],
            },
        ),
    ]
