# Generated by Django 5.0.2 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_to_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='The Outlook mailbox email address', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name of the mailbox owner', max_length=255)),
                ('mailbox_id', models.CharField(blank=True, help_text='Microsoft Graph user/mailbox ID', max_length=255)),
                ('access_token', models.TextField(help_text='Microsoft Graph API access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token for token renewal', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of granted scopes', null=True)),
                ('azure_tenant_id', models.CharField(blank=True, help_text='Azure AD tenant ID', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mailbox should be processed for tickets')),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=False, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('folder_to_watch', models.CharField(default='Inbox', help_text='Mail folder to watch for new emails (e.g., Inbox)', max_length=100)),
                ('mark_as_read', models.BooleanField(default=True, help_text='Mark emails as read after processing')),
                ('move_to_folder', models.CharField(blank=True, help_text='Optionally move processed emails to this folder', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time emails were fetched from this mailbox', null=True)),
            ],
            options={
                'verbose_name': 'Outlook Mailbox',
                'verbose_name_plural': 'Outlook Mailboxes',
                'ordering': ['-created_at'],
            },
        ),
    ]
