# Generated by Django 5.0.2 on 2026-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_to_ticket', '0002_add_outlook_mailbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIMAPMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address for this mailbox', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name for this mailbox', max_length=255)),
                ('imap_host', models.CharField(help_text='IMAP server hostname (e.g., imap.gmail.com)', max_length=255)),
                ('imap_port', models.IntegerField(default=993, help_text='IMAP server port (993 for SSL, 143 for non-SSL)')),
                ('imap_use_ssl', models.BooleanField(default=True, help_text='Use SSL/TLS for IMAP connection')),
                ('smtp_host', models.CharField(help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL, 25 for non-secure)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP connection')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP connection')),
                ('username', models.CharField(help_text='Username for authentication (usually email address)', max_length=255)),
                ('password', models.CharField(help_text='Password or app-specific password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mailbox should be processed for tickets')),
                ('auto_create_tickets', models.BooleanField(default=True, help_text='Automatically create tickets from incoming emails')),
                ('auto_reply', models.BooleanField(default=False, help_text='Send automatic reply when ticket is created')),
                ('default_priority', models.CharField(default='normal', help_text='Default priority for tickets created from emails', max_length=20)),
                ('folder_to_watch', models.CharField(default='INBOX', help_text='Mail folder to watch for new emails (e.g., INBOX)', max_length=100)),
                ('mark_as_read', models.BooleanField(default=True, help_text='Mark emails as read after processing')),
                ('move_to_folder', models.CharField(blank=True, help_text='Optionally move processed emails to this folder', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time emails were fetched from this mailbox', null=True)),
            ],
            options={
                'verbose_name': 'Custom IMAP Mailbox',
                'verbose_name_plural': 'Custom IMAP Mailboxes',
                'ordering': ['-created_at'],
            },
        ),
    ]
