# Generated by Django 5.0.2 on 2026-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_to_ticket', '0003_customimapmailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimapmailbox',
            name='enable_smtp',
            field=models.BooleanField(default=False, help_text='Enable outgoing email (SMTP) for this mailbox'),
        ),
        migrations.AlterField(
            model_name='customimapmailbox',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255),
        ),
    ]
