# Generated by Django 5.0.2 on 2026-02-24 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('can_manage_businesses', models.BooleanField(default=True)),
                ('can_manage_packages', models.BooleanField(default=False)),
                ('can_manage_billing', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_manage_admins', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_agents', models.IntegerField(default=5, help_text='Maximum number of agents allowed')),
                ('max_customers', models.IntegerField(default=100, help_text='Maximum number of customers allowed')),
                ('max_tickets_per_month', models.IntegerField(default=500, help_text='Maximum tickets per month')),
                ('storage_limit_gb', models.IntegerField(default=5, help_text='Storage limit in GB')),
                ('features', models.JSONField(default=list, help_text='List of feature keys enabled')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as recommended plan')),
                ('display_order', models.IntegerField(default=0)),
                ('badge_text', models.CharField(blank=True, help_text='e.g., "Most Popular"', max_length=50)),
                ('badge_color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('activate', 'Activated'), ('deactivate', 'Deactivated'), ('login', 'Logged In'), ('logout', 'Logged Out')], max_length=20)),
                ('target_type', models.CharField(help_text='Model name of target', max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='backoffice.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(help_text='Tenant schema name', max_length=63, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('custom_max_agents', models.IntegerField(blank=True, null=True)),
                ('custom_max_customers', models.IntegerField(blank=True, null=True)),
                ('custom_storage_limit_gb', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='backoffice.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('upgrade', 'Plan Upgrade'), ('downgrade', 'Plan Downgrade'), ('addon', 'Add-on Purchase'), ('refund', 'Refund'), ('credit', 'Credit Applied'), ('adjustment', 'Manual Adjustment')], default='subscription', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_url', models.URLField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='backoffice.subscription')),
            ],
            options={
                'verbose_name_plural': 'Billing history',
                'ordering': ['-created_at'],
            },
        ),
    ]
